Conflicts Resolved
ONDC-Official/reference-implementations pull request #90
Opened 2024-09-27 07:34 UTC by sonalishakya

2024-10-15 05:07 UTC, tanyamadaan requested changes

2024-10-15 05:07 UTC, tanyamadaan commented on utilities/logistics-b2b/log-verification-utility/utils/b2c-exports/utility.js
> +        if (tag?.descriptor?.code === "buyer_id") {
This could have been added to schema itself. Why need custom script for this?

2024-10-15 05:07 UTC, tanyamadaan commented on utilities/logistics-b2b/log-verification-utility/utils/b2c-exports/utility.js
> +  if (data.message.order.items.some(item => item.id === "BUYER_TERMS")) {
Can be added to schema itself.

2024-10-15 05:07 UTC, tanyamadaan commented on utilities/logistics-b2b/log-verification-utility/utils/b2c-exports/utility.js
A lot of these checks shud be added as part of schema itself. Please do the needful.

2024-10-22 11:46 UTC, sonalishakya commented on utilities/logistics-b2b/log-verification-utility/schema/B2C_exp_json_schema/keywords/confirm.js
> +  isFutureDated: (data) => {
Created a new keywords folder across all domains

2024-10-22 11:47 UTC, sonalishakya commented
Updated as per the comments

2024-11-04 07:08 UTC, tanyamadaan approved these changes

2024-11-04 07:09 UTC, merged